export const importPath = `package:async_redux/async_redux.dart`
export const importStatement = `import '${importPath}';`
export const actionsDirectory = "actions"
export const actionBaseName = "ReduxAction"
export const stateName = `AppState`
export const widgetSuffix = `Widget`
export const connectorSuffix = `Widget`
export const viewModelBaseName = `Vm`
export const viewModelFactoryBaseName = `VmFactory`
