name: tag

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  tag:
    if: "!contains(github.event.head_commit.message, 'CI: bumps version to ')"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - name: "Bump package version and create tag"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          major-wording: "major:"
          minor-wording: "minor:"
          tag-prefix: "v"
          commit-message: "CI: bumps version to {{version}}"
