name: publish

on:
  push:
    tags:
      - "*"

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v2

      - name: "Setup Node"
        uses: actions/setup-node@v2

      - name: "Install dependencies"
        run: |
          npm install
          npm install -g vsce

      - name: "Package extension"
        run: vsce package --out dart-move-symbol.vsix
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: "Publish to GitHub"
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dart-move-symbol.vsix"
          token: ${{ secrets.GITHUB_TOKEN }}
